### ISSUE TITLE
Playing again process does not work

### ISSUE THREAD

**Issue by StKyr** [VissaMoutafis/Snake_Game_in_Cpp#5]
When prompted:
> Do you want to play again? (yes or no):

I get 
> Exiting ...

no matter what I type.

Also, if you fix it, could you make it *also* work by simply typing `y` rather than `yes`?

**Comment by StKyr** [comment]
I did some debugging and printed the value of the `ans` string of `Game.cpp`.
Interestingly enough, I get values like:

> "AAAAAAAAAAyes"

or

> "BBBBBBBByes"

I think this happens when, in the moments before losing, I had been pressing arrow buttons, whose numerical values are translated to ASCII and then read via the `>>` operator into `ans`.

I would assume one way to fix this would be to "empty" the stdin buffer before prompting the play again message. A faster fix would probably be just to check whether `ans` ends in `"yes"` rather than `== "yes"`.

**Comment by VissaMoutafis** [comment]
Noted... I'll add a fix when possible

**Comment by VissaMoutafis** [comment]
I add the fix, finally!
If you like play again to check that but I think everything is alright now.
Thanks for noticing. If no further comment is done this issue will close in 24 hours.

**Comment by StKyr** [comment]
Seems to be working now!
